import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Image, Check, TrendingUp, MousePointerClick } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PublicLayout } from "@/components/layout/public-layout";
import { useI18n } from "@/lib/i18n";

export default function ThumbnailMaker() {
  const { t, locale } = useI18n();
  const isPt = locale === "pt";

  const features = isPt ? [
    "Análise de CTR por contraste de cores e tipografia",
    "Expressões faciais de alto impacto geradas por IA",
    "Templates baseados nos canais com mais visualizações",
    "Criação de logotipos com identidade visual consistente",
    "Tamanhos para YouTube, Instagram e Facebook Ads",
    "Download em PNG/JPG em alta resolução",
  ] : [
    "CTR analysis by color contrast and typography",
    "High-impact facial expressions generated by AI",
    "Templates based on highest-viewed channels",
    "Logo creation with consistent visual identity",
    "Sizes for YouTube, Instagram and Facebook Ads",
    "Download in high-resolution PNG/JPG",
  ];

  return (
    <PublicLayout>
      <div className="container mx-auto max-w-5xl px-4 py-12 space-y-20">
        <Link href="/">
          <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground gap-2">
            <ArrowLeft className="w-4 h-4" /> {t("tool_page.back")}
          </Button>
        </Link>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center space-y-6">
          <div className="inline-flex w-20 h-20 rounded-3xl bg-amber-500/10 items-center justify-center mx-auto">
            <Image className="w-10 h-10 text-amber-400" />
          </div>
          <Badge variant="outline" className="bg-amber-500/10 text-amber-400 border-amber-500/20 px-4 py-1 text-xs uppercase tracking-widest">
            {isPt ? "Design com IA" : "AI Design"}
          </Badge>
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight">
            {t("tool.thumbnail.name")}
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            {isPt
              ? "Thumbnails e logotipos com alta taxa de clique (CTR), com contraste otimizado por IA e expressões faciais impactantes que param o scroll."
              : "Thumbnails and logos with high click-through rates (CTR), with AI-optimized contrast and impactful facial expressions that stop the scroll."}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-2">
            <Link href="/register">
              <Button size="lg" className="rounded-full px-8 bg-gradient-to-r from-amber-500 to-orange-600 hover:shadow-lg hover:shadow-amber-500/25 transition-all">
                {t("tool_page.try_now")} <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
            <Link href="/pricing">
              <Button size="lg" variant="outline" className="rounded-full px-8 border-border/60">
                {t("tool_page.see_plans")}
              </Button>
            </Link>
          </div>
        </motion.div>

        <div className="grid grid-cols-3 gap-6">
          {[
            { value: "+40%", label: isPt ? "Aumento de CTR" : "CTR increase" },
            { value: "4K", label: isPt ? "Resolução máx." : "Max resolution" },
            { value: "<30s", label: isPt ? "Tempo de geração" : "Generation time" },
          ].map((stat, i) => (
            <div key={i} className="text-center p-6 rounded-2xl bg-background border border-border/50">
              <div className="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-amber-400 to-orange-500">{stat.value}</div>
              <div className="text-sm text-muted-foreground mt-1">{stat.label}</div>
            </div>
          ))}
        </div>

        <div className="space-y-8">
          <h2 className="text-3xl font-bold text-center">{t("tool_page.features")}</h2>
          <div className="grid md:grid-cols-2 gap-3">
            {features.map((f, i) => (
              <div key={i} className="flex items-center gap-3 p-4 rounded-xl bg-background border border-border/50">
                <div className="w-6 h-6 rounded-full bg-amber-500/10 flex items-center justify-center shrink-0">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                </div>
                <span className="text-sm">{f}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="text-center space-y-6 py-8 rounded-2xl bg-gradient-to-br from-amber-500/10 via-background to-orange-600/10 border border-amber-500/20 px-8">
          <MousePointerClick className="w-8 h-8 text-amber-400 mx-auto" />
          <h2 className="text-3xl font-bold">{t("tool_page.login_required")}</h2>
          <Link href="/register">
            <Button size="lg" className="rounded-full px-8 bg-gradient-to-r from-amber-500 to-orange-600 hover:shadow-lg hover:shadow-amber-500/25 transition-all">
              {t("tool_page.create_account")} <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </Link>
        </div>
      </div>
    </PublicLayout>
  );
}
