import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Film, Zap, Check, TrendingUp, Play, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PublicLayout } from "@/components/layout/public-layout";
import { useI18n } from "@/lib/i18n";

export default function ViralReels() {
  const { t, locale } = useI18n();
  const isPt = locale === "pt";

  const features = isPt ? [
    "Formato vertical 9:16 otimizado para Instagram Reels e TikTok",
    "Legendas dinâmicas geradas automaticamente com IA",
    "Ganchos de retenção psicológicos nos primeiros 3 segundos",
    "Música de fundo livre de direitos autorais",
    "CTA automático baseado no objetivo do vídeo",
    "Exportação direta para MP4 em alta resolução",
  ] : [
    "Vertical 9:16 format optimized for Instagram Reels and TikTok",
    "Dynamic captions automatically generated by AI",
    "Psychological retention hooks in the first 3 seconds",
    "Royalty-free background music",
    "Automatic CTA based on video objective",
    "Direct export to high-resolution MP4",
  ];

  return (
    <PublicLayout>
      <div className="container mx-auto max-w-5xl px-4 py-12 space-y-20">
        <Link href="/">
          <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground gap-2">
            <ArrowLeft className="w-4 h-4" /> {t("tool_page.back")}
          </Button>
        </Link>

        {/* Hero */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center space-y-6">
          <div className="inline-flex w-20 h-20 rounded-3xl bg-violet-500/10 items-center justify-center mx-auto">
            <Film className="w-10 h-10 text-violet-400" />
          </div>
          <Badge variant="outline" className="bg-violet-500/10 text-violet-400 border-violet-500/20 px-4 py-1 text-xs uppercase tracking-widest">
            {isPt ? "Gerador de Vídeo" : "Video Generator"}
          </Badge>
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight">
            {t("tool.viral_reels.name")}
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            {isPt
              ? "Vídeos verticais automatizados para Instagram e TikTok com legendas dinâmicas, ganchos psicológicos e música otimizada para o algoritmo."
              : "Automated vertical videos for Instagram and TikTok with dynamic captions, psychological hooks, and algorithm-optimized music."}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-2">
            <Link href="/register">
              <Button size="lg" className="rounded-full px-8 bg-gradient-to-r from-violet-500 to-purple-600 hover:shadow-lg hover:shadow-violet-500/25 transition-all">
                {t("tool_page.try_now")} <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
            <Link href="/pricing">
              <Button size="lg" variant="outline" className="rounded-full px-8 border-border/60">
                {t("tool_page.see_plans")}
              </Button>
            </Link>
          </div>
        </motion.div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-6">
          {[
            { value: "3s", label: isPt ? "Hook inicial" : "Initial hook" },
            { value: "9:16", label: isPt ? "Formato viral" : "Viral format" },
            { value: "4K", label: isPt ? "Resolução" : "Resolution" },
          ].map((stat, i) => (
            <div key={i} className="text-center p-6 rounded-2xl bg-background border border-border/50">
              <div className="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-violet-400 to-purple-500">{stat.value}</div>
              <div className="text-sm text-muted-foreground mt-1">{stat.label}</div>
            </div>
          ))}
        </div>

        {/* How it works */}
        <div className="space-y-8">
          <h2 className="text-3xl font-bold text-center">{t("tool_page.how_works")}</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {(isPt ? [
              { step: "01", title: "Tema do Vídeo", desc: "Digite o tema ou produto e o objetivo do Reel (vender, engajar, entreter)." },
              { step: "02", title: "IA Monta o Roteiro", desc: "Criamos o script com hook psicológico, desenvolvimento e CTA otimizados." },
              { step: "03", title: "Vídeo Pronto", desc: "Exportamos o vídeo com legendas, música e logo da sua marca." },
            ] : [
              { step: "01", title: "Video Theme", desc: "Enter the theme or product and the Reel objective (sell, engage, entertain)." },
              { step: "02", title: "AI Writes the Script", desc: "We create the script with psychological hook, development and optimized CTA." },
              { step: "03", title: "Video Ready", desc: "We export the video with captions, music and your brand logo." },
            ]).map((s, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="p-6 rounded-2xl bg-background border border-border/50 text-center space-y-3">
                <span className="text-4xl font-black text-primary/20">{s.step}</span>
                <h3 className="text-lg font-bold">{s.title}</h3>
                <p className="text-sm text-muted-foreground">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Features */}
        <div className="space-y-8">
          <h2 className="text-3xl font-bold text-center">{t("tool_page.features")}</h2>
          <div className="grid md:grid-cols-2 gap-3">
            {features.map((f, i) => (
              <div key={i} className="flex items-center gap-3 p-4 rounded-xl bg-background border border-border/50">
                <div className="w-6 h-6 rounded-full bg-violet-500/10 flex items-center justify-center shrink-0">
                  <Check className="w-3.5 h-3.5 text-violet-400" />
                </div>
                <span className="text-sm">{f}</span>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="text-center space-y-6 py-8 rounded-2xl bg-gradient-to-br from-violet-500/10 via-background to-purple-600/10 border border-violet-500/20 px-8">
          <TrendingUp className="w-8 h-8 text-violet-400 mx-auto" />
          <h2 className="text-3xl font-bold">{t("tool_page.login_required")}</h2>
          <Link href="/register">
            <Button size="lg" className="rounded-full px-8 bg-gradient-to-r from-violet-500 to-purple-600 hover:shadow-lg hover:shadow-violet-500/25 transition-all">
              {t("tool_page.create_account")} <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </Link>
        </div>
      </div>
    </PublicLayout>
  );
}
